### ISSUE TITLE
Weird Build Error on linux

### ISSUE THREAD

**Issue by villelahdenvuo** [ntkme/sass-embedded-host-ruby#33]
Hey, I'm using Jekyll with sass-embedded and it's working fine on my MacBook, but I have this strange error on the CI server:

```
current directory: /home/circleci/repo/vendor/bundle/ruby/3.1.0/gems/sass-embedded-1.4.2/ext/sass
/usr/local/bin/ruby -I/usr/local/lib/ruby/3.1.0 -rrubygems /home/circleci/repo/vendor/bundle/ruby/3.1.0/gems/rake-12.3.3/exe/rake RUBYARCHDIR\=/home/circleci/repo/vendor/bundle/ruby/3.1.0/extensions/x86_64-linux/3.1.0-static/sass-embedded-1.4.2 RUBYLIBDIR\=/home/circleci/repo/vendor/bundle/ruby/3.1.0/extensions/x86_64-linux/3.1.0-static/sass-embedded-1.4.2
fetch https://github.com/sass/dart-sass-embedded/releases/download/1.50.0/sass_embedded-1.50.0-linux-x64.tar.gz
rake aborted!
ArgumentError: wrong number of arguments (given 2, expected 1)
/home/circleci/repo/vendor/bundle/ruby/3.1.0/gems/sass-embedded-1.4.2/ext/sass/Rakefile:57:in `unarchive'
/home/circleci/repo/vendor/bundle/ruby/3.1.0/gems/sass-embedded-1.4.2/ext/sass/Rakefile:20:in `block in <top (required)>'
/home/circleci/repo/vendor/bundle/ruby/3.1.0/gems/rake-12.3.3/exe/rake:27:in `<main>'
Tasks: TOP => default => install => sass_embedded
(See full trace by running task with --trace)

rake failed, exit code 1
```

But when I look at that line of code, it looks correct to me: `mkdir_p dest`.

**Comment by villelahdenvuo** [comment]
Looks like downgrading to ruby 2.7 made everything work. Still I guess it should work fine on 3.1 as well as it does on my laptop?

**Comment by ntkme** [comment]
The installation has been tested on linux ruby 3.1.1 on GitHub Actions. It should work.

I also tested locally with ruby 3.1.0 and was not able to reproduce this issue:

```
(ruby:3.1.0)root@354a0afcd44a:~# gem install sass-embedded
Fetching sass-embedded-1.4.2.gem
Fetching google-protobuf-3.20.0-x86_64-linux.gem
Successfully installed google-protobuf-3.20.0-x86_64-linux
Building native extensions. This could take a while...
Successfully installed sass-embedded-1.4.2
2 gems installed
```

@villelahdenvuo Can please you try `gem install sass-embedded --verbose` in that environment and paste the verbose installation output?

**Comment by villelahdenvuo** [comment]
This is getting more strange. The gem install command succeeds:

```
Building native extensions. This could take a while...
current directory: /home/circleci/.rubygems/gems/sass-embedded-1.4.2/ext/sass
["/usr/local/bin/ruby", "-I/usr/local/lib/ruby/site_ruby/3.1.0", "-rrubygems", "/usr/local/lib/ruby/gems/3.1.0/gems/rake-13.0.6/exe/rake", "RUBYARCHDIR=/home/circleci/.rubygems/extensions/x86_64-linux/3.1.0/sass-embedded-1.4.2", "RUBYLIBDIR=/home/circleci/.rubygems/extensions/x86_64-linux/3.1.0/sass-embedded-1.4.2"]
fetch https://github.com/sass/dart-sass-embedded/releases/download/1.50.0/sass_embedded-1.50.0-linux-x64.tar.gz
tar -vxC . -f sass_embedded-1.50.0-linux-x64.tar.gz
mkdir -p .
sass_embedded/src/LICENSE
sass_embedded/dart-sass-embedded
rm sass_embedded-1.50.0-linux-x64.tar.gz
fetch https://github.com/sass/embedded-protocol/raw/1.0.0/embedded_sass.proto
fetch https://repo.maven.apache.org/maven2/com/google/protobuf/protoc/3.20.0/protoc-3.20.0-linux-x86_64.exe
./protoc.exe --proto_path=. --ruby_out=. embedded_sass.proto
chmod a+x protoc.exe
current directory: /home/circleci/.rubygems/gems/sass-embedded-1.4.2/ext/sass
/usr/local/bin/ruby -I/usr/local/lib/ruby/site_ruby/3.1.0 -rrubygems /usr/local/lib/ruby/gems/3.1.0/gems/rake-13.0.6/exe/rake RUBYARCHDIR\=/home/circleci/.rubygems/extensions/x86_64-linux/3.1.0/sass-embedded-1.4.2 RUBYLIBDIR\=/home/circleci/.rubygems/extensions/x86_64-linux/3.1.0/sass-embedded-1.4.2
Successfully installed sass-embedded-1.4.2
2 gems installed
circleci@155928426cc5:~/repo$ ruby -v
ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [x86_64-linux]
```

But using bundler it fails:

```
Building native extensions. This could take a while...
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /home/circleci/repo/vendor/bundle/ruby/3.1.0/gems/sass-embedded-1.4.2/ext/sass
/usr/local/bin/ruby -I/usr/local/lib/ruby/site_ruby/3.1.0 -rrubygems /home/circleci/repo/vendor/bundle/ruby/3.1.0/gems/rake-12.3.3/exe/rake
RUBYARCHDIR\=/home/circleci/repo/vendor/bundle/ruby/3.1.0/extensions/x86_64-linux/3.1.0/sass-embedded-1.4.2
RUBYLIBDIR\=/home/circleci/repo/vendor/bundle/ruby/3.1.0/extensions/x86_64-linux/3.1.0/sass-embedded-1.4.2
fetch https://github.com/sass/dart-sass-embedded/releases/download/1.50.0/sass_embedded-1.50.0-linux-x64.tar.gz
rake aborted!
ArgumentError: wrong number of arguments (given 2, expected 1)
/home/circleci/repo/vendor/bundle/ruby/3.1.0/gems/sass-embedded-1.4.2/ext/sass/Rakefile:57:in `unarchive'
/home/circleci/repo/vendor/bundle/ruby/3.1.0/gems/sass-embedded-1.4.2/ext/sass/Rakefile:20:in `block in <top (required)>'
/home/circleci/repo/vendor/bundle/ruby/3.1.0/gems/rake-12.3.3/exe/rake:27:in `<main>'
Tasks: TOP => default => install => sass_embedded
(See full trace by running task with --trace)

rake failed, exit code 1

Gem files will remain installed in /home/circleci/repo/vendor/bundle/ruby/3.1.0/gems/sass-embedded-1.4.2 for inspection.
Results logged to /home/circleci/repo/vendor/bundle/ruby/3.1.0/extensions/x86_64-linux/3.1.0/sass-embedded-1.4.2/gem_make.out

  /usr/local/lib/ruby/site_ruby/3.1.0/rubygems/ext/builder.rb:95:in `run'
  /usr/local/lib/ruby/site_ruby/3.1.0/rubygems/ext/rake_builder.rb:28:in `build'
  /usr/local/lib/ruby/site_ruby/3.1.0/rubygems/ext/builder.rb:164:in `build_extension'
  /usr/local/lib/ruby/site_ruby/3.1.0/rubygems/ext/builder.rb:198:in `block in build_extensions'
  /usr/local/lib/ruby/site_ruby/3.1.0/rubygems/ext/builder.rb:195:in `each'
  /usr/local/lib/ruby/site_ruby/3.1.0/rubygems/ext/builder.rb:195:in `build_extensions'
  /usr/local/lib/ruby/site_ruby/3.1.0/rubygems/installer.rb:853:in `build_extensions'
  /usr/local/lib/ruby/site_ruby/3.1.0/bundler/rubygems_gem_installer.rb:71:in `build_extensions'
  /usr/local/lib/ruby/site_ruby/3.1.0/bundler/rubygems_gem_installer.rb:28:in `install'
  /usr/local/lib/ruby/site_ruby/3.1.0/bundler/source/rubygems.rb:204:in `install'
  /usr/local/lib/ruby/site_ruby/3.1.0/bundler/installer/gem_installer.rb:54:in `install'
  /usr/local/lib/ruby/site_ruby/3.1.0/bundler/installer/gem_installer.rb:16:in `install_from_spec'
  /usr/local/lib/ruby/site_ruby/3.1.0/bundler/installer/parallel_installer.rb:186:in `do_install'
  /usr/local/lib/ruby/site_ruby/3.1.0/bundler/installer/parallel_installer.rb:177:in `block in worker_pool'
  /usr/local/lib/ruby/site_ruby/3.1.0/bundler/worker.rb:62:in `apply_func'
  /usr/local/lib/ruby/site_ruby/3.1.0/bundler/worker.rb:57:in `block in process_queue'
  /usr/local/lib/ruby/site_ruby/3.1.0/bundler/worker.rb:54:in `loop'
  /usr/local/lib/ruby/site_ruby/3.1.0/bundler/worker.rb:54:in `process_queue'
  /usr/local/lib/ruby/site_ruby/3.1.0/bundler/worker.rb:91:in `block (2 levels) in create_threads'

An error occurred while installing sass-embedded (1.4.2), and Bundler cannot continue.

In Gemfile:
  sass-embedded
Bundler::InstallError: Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /home/circleci/repo/vendor/bundle/ruby/3.1.0/gems/sass-embedded-1.4.2/ext/sass
/usr/local/bin/ruby -I/usr/local/lib/ruby/site_ruby/3.1.0 -rrubygems /home/circleci/repo/vendor/bundle/ruby/3.1.0/gems/rake-12.3.3/exe/rake RUBYARCHDIR\=/home/circleci/repo/vendor/bundle/ruby/3.1.0/extensions/x86_64-linux/3.1.0/sass-embedded-1.4.2 RUBYLIBDIR\=/home/circleci/repo/vendor/bundle/ruby/3.1.0/extensions/x86_64-linux/3.1.0/sass-embedded-1.4.2
fetch https://github.com/sass/dart-sass-embedded/releases/download/1.50.0/sass_embedded-1.50.0-linux-x64.tar.gz
rake aborted!
ArgumentError: wrong number of arguments (given 2, expected 1)
/home/circleci/repo/vendor/bundle/ruby/3.1.0/gems/sass-embedded-1.4.2/ext/sass/Rakefile:57:in `unarchive'
/home/circleci/repo/vendor/bundle/ruby/3.1.0/gems/sass-embedded-1.4.2/ext/sass/Rakefile:20:in `block in <top (required)>'
/home/circleci/repo/vendor/bundle/ruby/3.1.0/gems/rake-12.3.3/exe/rake:27:in `<main>'
Tasks: TOP => default => install => sass_embedded
(See full trace by running task with --trace)

rake failed, exit code 1

Gem files will remain installed in /home/circleci/repo/vendor/bundle/ruby/3.1.0/gems/sass-embedded-1.4.2 for inspection.
Results logged to /home/circleci/repo/vendor/bundle/ruby/3.1.0/extensions/x86_64-linux/3.1.0/sass-embedded-1.4.2/gem_make.out

  /usr/local/lib/ruby/site_ruby/3.1.0/rubygems/ext/builder.rb:95:in `run'
  /usr/local/lib/ruby/site_ruby/3.1.0/rubygems/ext/rake_builder.rb:28:in `build'
  /usr/local/lib/ruby/site_ruby/3.1.0/rubygems/ext/builder.rb:164:in `build_extension'
  /usr/local/lib/ruby/site_ruby/3.1.0/rubygems/ext/builder.rb:198:in `block in build_extensions'
  /usr/local/lib/ruby/site_ruby/3.1.0/rubygems/ext/builder.rb:195:in `each'
  /usr/local/lib/ruby/site_ruby/3.1.0/rubygems/ext/builder.rb:195:in `build_extensions'
  /usr/local/lib/ruby/site_ruby/3.1.0/rubygems/installer.rb:853:in `build_extensions'
  /usr/local/lib/ruby/site_ruby/3.1.0/bundler/rubygems_gem_installer.rb:71:in `build_extensions'
  /usr/local/lib/ruby/site_ruby/3.1.0/bundler/rubygems_gem_installer.rb:28:in `install'
  /usr/local/lib/ruby/site_ruby/3.1.0/bundler/source/rubygems.rb:204:in `install'
  /usr/local/lib/ruby/site_ruby/3.1.0/bundler/installer/gem_installer.rb:54:in `install'
  /usr/local/lib/ruby/site_ruby/3.1.0/bundler/installer/gem_installer.rb:16:in `install_from_spec'
  /usr/local/lib/ruby/site_ruby/3.1.0/bundler/installer/parallel_installer.rb:186:in `do_install'
  /usr/local/lib/ruby/site_ruby/3.1.0/bundler/installer/parallel_installer.rb:177:in `block in worker_pool'
  /usr/local/lib/ruby/site_ruby/3.1.0/bundler/worker.rb:62:in `apply_func'
  /usr/local/lib/ruby/site_ruby/3.1.0/bundler/worker.rb:57:in `block in process_queue'
  /usr/local/lib/ruby/site_ruby/3.1.0/bundler/worker.rb:54:in `loop'
  /usr/local/lib/ruby/site_ruby/3.1.0/bundler/worker.rb:54:in `process_queue'
  /usr/local/lib/ruby/site_ruby/3.1.0/bundler/worker.rb:91:in `block (2 levels) in create_threads'

An error occurred while installing sass-embedded (1.4.2), and Bundler cannot continue.
```

I finally noticed that I had ` spec.add_development_dependency "rake", "~> 12.3.3"` in my gemspec, updating it to `13.0.6` fixed the bundle install. It's weird that it worked locally just fine and worked with ruby 2.7.
